### ISSUE TITLE
Issue with trough queue

### ISSUE THREAD

**Issue by jacobneckmar** [hunterbdm/DeadAss-Splash#15]
At the powerphase drop (after the redesigned splash) there was no indication from the bruteforce tasks that they were trough splash

**Comment by aslatt13** [comment]
A workaround would be to click Show/Hide on each instance so you can see, otherwise you wont be able to tell. Needs to be fixed at some point.

**Comment by yeeezy** [comment]
I have a PR open to fix the issue

https://github.com/hunterbdm/Deadass-Splash/pull/16
