### ISSUE TITLE
ATC Failed

### ISSUE THREAD

**Issue by JoelWaddellac** [hunterbdm/DeadAss-Splash#2]
![atc failed](https://user-images.githubusercontent.com/23046851/27454053-2e53bd72-575e-11e7-9ddf-6cb9c5386a2e.JPG)
![atc failed console](https://user-images.githubusercontent.com/23046851/27454058-30a57700-575e-11e7-91aa-2dbdb5d6bdc9.JPG)

Getting ATC failed everytime I try and cart. No caught exceptions or errors in console window.

**Comment by hunterbdm** [comment]
Many things can cause ATC Failure, such as
1. Size out of stock (Most likely in this case)
2. Invalid Sitekey in settings
3. Invalid Form JSON in settings
4. Sometimes ATCs will randomly fail.
