### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by JustrynaLearn** [hunterbdm/DeadAss-Splash#3]
Hi,
Firstly would like to say A BIG BIG THANK YOU FOR THIS. 
I am just stuck however at the cart task section. i've followed every step but when i reach the cart tasks section it's just stuck at 'getting captcha'. any idea why?
Thanks in advance for your help.

**Comment by hunterbdm** [comment]
Watch video tutorial, you need to start the captcha harvester.
