### ISSUE TITLE
Not working on mac

### ISSUE THREAD

**Issue by Smrphy** [hunterbdm/DeadAss-Splash#6]
Hello,
I am trying to do this on a mac. I have terminal open, node downloaded, and the deadass splash file copied. I enter cd [deadass file], npm install, and then npm install electron but it never works and this is what i get for hours. 

Seans-MacBook-Pro:~ Sean$ cd /Users/Sean/Downloads/DeadAss-Splash-master 
Seans-MacBook-Pro:DeadAss-Splash-master Sean$ npm install
npm WARN deadass-splash@1.0.0 No repository field.
Seans-MacBook-Pro:DeadAss-Splash-master Sean$ npm install electron

> electron@1.6.11 postinstall /Users/Sean/Downloads/DeadAss-Splash-master/node_modules/electron
> node install.js

What should I do? thx

**Comment by harveywoodall** [comment]
try `npm start`
does it work?

**Comment by Smrphy** [comment]
no it does nothing when i hit enter

**Comment by harveywoodall** [comment]
try installing node again, it wasnt working for me a the start but when i reinstall node it was fine

**Comment by Smrphy** [comment]
I tried doing that before and it didnt work. But i just tried it again and it did thank you man!

**Comment by harveywoodall** [comment]
ahh brilliant! Glad to have helped
