### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by lello98** [hunterbdm/DeadAss-Splash#9]
When i try to add to cart with captcha they disappear 
Could you help me?

**Comment by hunterbdm** [comment]
Not descriptive enough.

**Comment by lello98** [comment]
I can t solve captcha and is imposisble to add to cart manually

**Comment by lello98** [comment]
When i try to solve capthas  the images disappear and is impossible to solve captchas

**Comment by hunterbdm** [comment]
So use 2captcha and the built in captcha harvester as shown in the video.

**Comment by hunterbdm** [comment]
If you can't solve the captcha in a bruteforce task you need to add your google cookies in the settings.
